[versions]
agp = "9.0.1"
androidTools = "32.2.1"
kotlin = "2.3.21"
coreKtx = "1.18.0"
cameraX = "1.6.1"
accompanist = "0.37.3"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
composeBom = "2026.06.00"
splashScreen = "1.2.0"
materialIconsExtended = "1.7.8"
appcompat = "1.7.1"
material = "1.14.0"
hilt = "2.59.2"
hiltNavigationCompose = "1.3.0"
ksp = "2.3.2"
room = "2.8.4"
androidxDataStore = "1.2.1"
gson = "2.14.0"
lottie = "6.7.1"
okhttp = "5.3.2"
chucker = "4.3.1"
kotlinxSerializationJson = "1.11.0"
kotlinxDatetime = "0.8.0"
retrofit = "3.0.0"

#play-services
playServiceAuth = "21.5.1"
playServiceBase = "18.10.0"
playServiceApiPhone = "18.3.0"
playServiceAppUpdate = "2.1.0"
playServiceAppReview = "2.0.2"

#firebase
googleServices = "4.4.4"
googleFirebaseAppdistribution = "5.2.1"
firebaseBom = "34.14.0"

#coil
coil = "3.5.0"

#WorkManager
workManager = "2.11.2"


nav3Core = "1.1.2"
lifecycleViewmodelNav3 = "2.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraX" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraX" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraX" }
androidx-camera-compose = { group = "androidx.camera", name = "camera-compose", version.ref = "cameraX" }

lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

# The helper library to grant the camera permission
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

# Icons
androidx-compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#WorkManager
androidx-work-manager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
androidx-work-manager-testing = { group = "androidx.work", name = "work-testing", version.ref = "workManager" }


# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

#coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-svg-compose = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }
coil-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

#timber
jakewharton-timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }


#firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-ai = { module = "com.google.firebase:firebase-ai" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }

# Networking
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# Serialization
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Chucker
chucker-library = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-library-no-op = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }

#Play-auth, update, review
play-service-api-phone = { group = "com.google.android.gms", name = "play-services-auth-api-phone", version.ref = "playServiceApiPhone" }
play-service-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServiceAuth" }
play-service-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "playServiceBase" }
play-service-app-update = { group = "com.google.android.play", name = "app-update", version.ref = "playServiceAppUpdate" }
play-service-app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "playServiceAppUpdate" }
play-service-app-review = { group = "com.google.android.play", name = "review", version.ref = "playServiceAppReview" }
play-service-app-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "playServiceAppReview" }

#room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

#datastore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-dataStore = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
androidx-dataStore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "androidxDataStore" }

# Core Navigation 3 libraries
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }


# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
room = { id = "androidx.room", version.ref = "room" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.7" }
google-firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "googleFirebaseAppdistribution" }


